version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "7000:7000"
    environment:
      - GF_SERVER_HTTP_PORT=7000
    volumes:
      - /home/ubuntu/docker-volume/volume/grafana:/var/lib/grafana
    networks:
      - br_app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "472:472"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - /home/ubuntu/docker-volume/volume/prometheus:/prometheus
    networks:
      - br_app
      
networks:
  br_app:
    external: true