version: '3'

services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    container_name: grafana
    ports:
      - "7000:7000"
    environment:
      - GF_SERVER_HTTP_PORT=7000
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=tscofet@gmail.com
      - GF_SMTP_PASSWORD=sksmscjswp!5
      - GF_SMTP_SKIP_VERIFY=true
    volumes:
      - /home/ubuntu/docker-volume/grafana/volume:/var/lib/grafana
    networks:
      - br_app

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    user: "472:472"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - /home/ubuntu/docker-volume/prometheus/volume:/prometheus
    networks:
      - br_app
      
networks:
  br_app:
    external: true