version: "3"
services:
  datagenerator-server-1:
    container_name: dev-back-green
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: "${CLIENT_PROFILE}"
    ports:
      - "8080:8080"
    networks:
      - br_app

networks:
  br_app:
    external: true

# CLIENT_PROFILE=client1 docker-compose up -d