groups:
- name: container_down
  rules:
  - alert: ContainerDown
    expr: absent(container_last_seen{name="your_container_name"})
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.name }} on server {{ $labels.instance }} is down"