global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator api'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['52.79.42.131:8091']

  - job_name: 'spring-actuator division'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['52.79.42.131:8090']

  - job_name: 'kafka'
    metrics_path: '/jmx'
    scrape_interval: 5s
    static_configs:
      - targets: ['54.180.130.90:9404', '3.38.186.82:9404', '43.201.41.201:9404', '3.34.43.153:9404', '52.78.98.144:9404']

rule_files:
  - "alert.rules.yml"
