global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator api'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['13.124.179.156:8091']

  - job_name: 'spring-actuator division'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['52.79.42.131:8090']

  - job_name: 'kafka'
    metrics_path: '/jmx'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.38.164.6:9404', '3.34.254.10:9404', '15.165.7.7:9404']

rule_files:
  - "alert.rules.yml"
