global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.36.67.11:8091', '3.36.67.11:8090']

  - job_name: 'kafka'
    metrics_path: '/jmx'
    scrape_interval: 5s
    static_configs:
      - targets: ['43.200.71.179:9404', '3.36.10.145:9404', '43.200.130.111:9404']