global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator api'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.36.96.3:8091']

  - job_name: 'spring-actuator division'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.36.96.3:8090']

  - job_name: 'kafka'
    metrics_path: '/jmx'
    scrape_interval: 5s
    static_configs:
      - targets: ['43.200.71.179:9404', '3.36.10.145:9404', '43.200.130.111:9404']

rule_files:
  - "alert.rules.yml"