version: "3"
services:
  # nginx
  dev-back-nginx:
    image: nginx:stable-alpine
    container_name: dev-back-nginx
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "8090:8090"
    networks:
      - br_log
      - br_app

networks:
  br_log:
    external: true
  br_app:
    external: true
