- name: 카프카 설치를 위한 플레이북
  hosts: kafka_server
  become: yes

  tasks:
    - name: docker-compose yaml 복사
      copy:
        src: docker-compose.yml
        dest: /opt/kafka/docker-compose.yml

    - name: docker-compose 실행
      command: docker-compose up -d
      args:
        chdir: /opt/kafka
