- name: 카프카 설치를 위한 플레이북
  hosts: kafka_server
  become: yes

  tasks:
    - name: Create /etc/kafka folder
      ansible.builtin.file:
        path: /etc/kafka
        state: directory
        mode: '0755'
        
    - name: docker-compose yaml 복사
      copy:
        src: docker-compose.yaml
        dest: /etc/kafka/docker-compose.yaml

    - name: docker-compose 실행
      command: docker-compose up -d
      args:
        chdir: /etc/kafka
