- name: data_division 배포
  hosts: main_server1
  vars:
    compose_file: "./data_division"
  tasks:
    - name: Create data_division directory
      file:
        path: ~/data_division
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: "{{ compose_file }}/docker-compose.yaml"
        dest: ~/data_division/docker-compose.yaml

    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: data_division 배포
      docker_compose:
        project_src: "~/data_division/docker-compose.yaml"
        state: present
        pull: yes
        remove_orphans: yes
        restarted: yes
