- name: api 배포
  hosts: main_server1
  vars:
    compose_file: "./data_api"
  tasks:
    - name: Create data_api directory
      file:
        path: ~/data_api
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: "{{ compose_file }}/docker-compose.yml"
        dest: ~/data_api/docker-compose.yml

    - name: 도커 실행중인지 확인
      service:
        name: docker
        state: started

    - name: api 배포
      docker_compose:
        project_src: "{{ compose_file }}"
        state: present
        pull: yes
        remove_orphans: yes
        restarted: yes
