- name: api 배포
  hosts: main_server
  vars:
    compose_file: "./data_api"
    container_name: "api"
    image_name: "scofe/api"
  tasks:
    - name: Create data_api directory
      file:
        path: ~/data_api
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: "{{ compose_file }}/docker-compose.yaml"
        dest: ~/data_api/docker-compose.yaml

    - name: Stop and remove existing Docker container
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes
      register: stop_result
      ignore_errors: yes

    - name: 도커 실행중인지 확인
      service:
        name: docker
        state: started

    - name: api 배포
      docker_compose:
        project_src: "~/data_api"
        state: present
        pull: yes
        remove_orphans: yes
        restarted: yes
