# https://chronosa.tistory.com/entry/RabbitMQ-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0-Feat-Docker

version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-stream
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - br_log
      - br_app

networks:
  br_log:
    external: true
  br_app:
    external: true