- name: data_division 배포
  hosts: data_division_server
  vars:
    compose_file: "./data_division"
    container_name: "data_division"
    image_name: "scofe/data_division"
  tasks:
    - name: Create data_division directory
      file:
        path: ~/data_division
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: "{{ compose_file }}/docker-compose.yaml"
        dest: ~/data_division/docker-compose.yaml

    - name: Stop and remove existing Docker container
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes
      register: stop_result
      ignore_errors: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: data_division 배포
      docker_compose:
        project_src: "~/data_division"
        state: present
        pull: yes
        remove_orphans: yes
        restarted: yes
