- name: Create Docker network br-app
  hosts: all
  become: yes
  tasks:
    - name: Check if br-app network exists
      ansible.builtin.command:
        cmd: docker network ls --filter name=br-app
      register: br_app_network
      changed_when: false

    - name: Create br-app network
      ansible.builtin.command:
        cmd: docker network create br-app
      when: "'br-app' not in br_app_network.stdout"

    - name: Create Docker group
      become: yes
      group:
        name: docker
        state: present
    
    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

    - name: Modify Docker socket permissions
      become: yes
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted