# 플레이북에는 하나 이상의 플레이가 있을 수 있습니다.
- name: Play 1 - Java OpenJDK 11 Install
  hosts: all # 이 플레이의 대상 호스트 (인벤토리 파일에서 정의됨)
  become: yes # 필요한 경우 권한을 상승시킵니다 (sudo로 권한 상승)
  tasks: # 이 플레이에 대해 실행할 작업 목록
    - name: apt update
      apt:
        update_cache: yes

    - name: Java OpenJDK 11 Install
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Java version check
      ansible.builtin.command:
        _raw_params: java --version

- name: 플레이 2 - 원격 호스트에 Docker & Docker-compose 설치 및 구성
  hosts: all
  become: yes
  tasks:
    - name: Docker 설치를 위한 필수 패키지 설치
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Docker 공식 GPG 키 추가
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Docker APT 리포지토리 추가
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Docker 설치
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Docker 서비스 활성화 및 시작
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Update Docker service configuration file
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/docker.service
        regexp: "^ExecStart="
        line: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375"
      become: yes

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: yes
      become: yes

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
      become: yes

    - name: Get Docker Compose URL
      ansible.builtin.shell: echo "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
      register: docker_compose_url

    - name: Download and install docker-compose
      ansible.builtin.get_url:
        url: "{{ docker_compose_url.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Check docker-compose version
      ansible.builtin.command:
        cmd: docker-compose --version
