version: "3"
services:
  # back - green
  dev-back-green:
    container_name: dev-back-green
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: "devgreen"
    ports:
      - "8092:8092"
    networks:
      - br_log
      - br_app

networks:
  br_log:
    external: true
  br_app:
    external: true
