- name: application-secret.yaml 배포
  hosts: data_instance_server
  become: yes
  tasks:
    - name: secret 폴더생성
      file:
        path: ~/secret
        state: directory

    - name: application-secret.yaml 파일 생성
      template:
        src: ./secret/application-secret.yaml.j2  # 템플릿 파일의 경로
        dest: ~/sercret/application-secret.yaml  # 생성할 파일의 경로