- name: Docker 컨테이너로 Spring Boot 애플리케이션 배포
  hosts: data_instance_server
  become: yes
  vars:
    app_image: scofe/data_generator

  tasks:
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present

    # 기존 이미지 제거
    - name: Remove existing Spring Boot Docker image
      ansible.builtin.docker_image:
        name: "{{ app_image }}"
        state: absent
      ignore_errors: yes

    # Docker 이미지를 끌어 오기
    - name: Pull Spring Boot Docker image
      ansible.builtin.docker_image:
        name: "{{ app_image }}"
        source: pull

    - name: Deploy container 1
      include_tasks: deploy_container.yml
      vars:
        app_container_name: spring_boot_app_container1
        app_profile: "{{ spring_profiles.container1[inventory_hostname] }}"
        app_port: 8080

    - name: Deploy container 2
      include_tasks: deploy_container.yml
      vars:
        app_container_name: spring_boot_app_container2
        app_profile: "{{ spring_profiles.container2[inventory_hostname] }}"
        app_port: 8081
