version: "3.7"
services:
  # 개발 데이터베이스
  mariadb:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "$MYSQL_PORT:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PWD
    volumes:
      # Data
      - type: bind
        source: $MYSQL_DIR/data
        target: /var/lib/mysql
        read_only: false
    networks:
      - br_app
      - br_log

networks:
  br_app:
    external: true
  br_log:
    external: true
