version: '3'
services:
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./confing/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093