all:
  # 인벤토리의 모든 호스트에 적용되는 그룹 수준 변수 정의
  # 이 경우 모든 호스트에 대해 변수를 설정한다.
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/etc/ansible/semsekey.pem"

  # 모든 하위 그룹을 포함하는 그룹정의
  # 아래의 그룹들을 all의 하위그룹으로 포함한다.
  children:
    ansible_server:
      hosts:
        10.0.1.2266:
    data_instance_server:
      hosts:
        10.0.1.241:
        10.0.1.226:
        10.0.1.87:
        10.0.1.235:
        10.0.1.73:
        10.0.1.22:
      vars:
        spring_profiles:
          container1:
            10.0.1.241: client1
            10.0.1.226: client3
            10.0.1.87: client5
            10.0.1.235: client7
            10.0.1.73: client9
            10.0.1.22: client11
          container2:
            10.0.1.241: client2
            10.0.1.226: client4
            10.0.1.87: client6
            10.0.1.235: client8
            10.0.1.73: client10
            10.0.1.22: client12
    kafka_server:
      hosts:
        10.0.1.212:
        10.0.1.114:
        10.0.1.227:
