all:
  # 인벤토리의 모든 호스트에 적용되는 그룹 수준 변수 정의
  # 이 경우 모든 호스트에 대해 변수를 설정한다.
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/etc/ansible/semsekey.pem"

  # 모든 하위 그룹을 포함하는 그룹정의
  # 아래의 그룹들을 all의 하위그룹으로 포함한다.
  children:
    ansible_server:
      hosts:
        10.0.1.244:
    data_instance_server:
      hosts:
        10.0.1.178:
          influxdb_token: "Q3i5GKnhvBbCaR5lBafqs7CPVskA_DB7muR3zPF4uw8xQm8J6hOkFAgojbHlFyLqVGNRVD-4qQiVYSahhu_mwA=="
        10.0.1.168:
          influxdb_token: "8WBHSkjwg3GWpJWJKOFIpdBlBCxEyss5Hy4e5POJaw4M2xXClLJgS526jt8Wr1PeVqDozm_-WMPgT8mJBOUtWQ=="
        10.0.1.65:
          influxdb_token: "MNPgnZ3WLMDw9dUL-Xf_A5dnStPRAXQkjjudjfw5pVSIxZepMOi1Pymyv8uaBsrwEUmPJ_m2E4JMpgXcssEtyg=="
        10.0.1.189:
          influxdb_token: "tbLgwVvqgfqcEzNLgFGEc2p8GUAFNai2EIxB2dnFWzguciXbOkXQLjwo2TyjebDQ0h69NafKHsrtlcntNISLjw=="
        10.0.1.51:
          influxdb_token: "jf0pGQqQWRWttxEXoDjd4G_BMi0rh_9ePreMRoxMflEibF9KqXTztIP7HjHoPo9nLEBWyR71N_aX_H32GOoHBg=="
        10.0.1.80:
          influxdb_token: "ys_llndABAtTx51FgN5xTKnE4_wrlcbqbtgXWqk-Rf_jVHn-tjPYbN4e3gG5WI7a65z2qNoXJQuzPNDjzsfbBg=="
      vars:
        spring_profiles:
          container1:
            10.0.1.178: client1
            10.0.1.168: client3
            10.0.1.65: client5
            10.0.1.189: client7
            10.0.1.51: client9
            10.0.1.80: client11
          container2:
            10.0.1.178: client2
            10.0.1.168: client4
            10.0.1.65: client6
            10.0.1.189: client8
            10.0.1.51: client10
            10.0.1.80: client12
    kafka_server:
      hosts:
        10.0.1.226:
        10.0.1.225:
        10.0.1.13:
