all:
  # 인벤토리의 모든 호스트에 적용되는 그룹 수준 변수 정의
  # 이 경우 모든 호스트에 대해 변수를 설정한다.
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/etc/ansible/semsekey.pem"

  # 모든 하위 그룹을 포함하는 그룹정의
  # 아래의 그룹들을 all의 하위그룹으로 포함한다.
  children:
    main_server:
      hosts: 43.201.55.255

    ansible_server:
      hosts:
        10.0.1.90:
    data_instance_server:
      hosts:
        10.0.1.127:
        10.0.1.9:
        10.0.1.34:
        10.0.1.114:
        10.0.1.47:
        10.0.1.19:
      vars:
        spring_profiles:
          container1:
            10.0.1.127: client1
            10.0.1.9: client3
            10.0.1.34: client5
            10.0.1.114: client7
            10.0.1.47: client9
            10.0.1.19: client11
          container2:
            10.0.1.127: client2
            10.0.1.9: client4
            10.0.1.34: client6
            10.0.1.114: client8
            10.0.1.47: client10
            10.0.1.19: client12
    kafka_server:
      hosts:
        10.0.1.29:
        10.0.1.214:
        10.0.1.130:
