all:
  # 인벤토리의 모든 호스트에 적용되는 그룹 수준 변수 정의
  # 이 경우 모든 호스트에 대해 변수를 설정한다.
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/etc/ansible/semsekey2.pem"

  # 모든 하위 그룹을 포함하는 그룹정의
  # 아래의 그룹들을 all의 하위그룹으로 포함한다.
  children:
    ansible_server:
      hosts:
        10.0.1.191:
    data_instance_server:
      hosts:
        10.0.1.178:
          influxdb_token: "sVbwgbUgvOoZ5JG9S8B-RobrQ7yQtHD7pmnuUwgWzFV9H5KtfsauV70h5rp7qkenVyRRX8NcE9Scv-3RszXumg=="
        10.0.1.168:
          influxdb_token: "BC99_vTe8Mua8htUYuOM7adzGKipn7JX78rCp6ePuUIfvLcW5QxDPv9t9b803E3iRLnaP58O1_rthU2kjXRFaQ=="
        10.0.1.65:
          influxdb_token: "EoVxpZ3vDdx-iy8FSY-pqa2BBGmyI6_GL9NVW9SlNvPfcs1l18Dt10IWwTeSd_zX526lanZ01yDzhreiTJhRCw=="
        10.0.1.189:
          influxdb_token: "xUCAOfL5o6FKUs6WhlEqfsEO3EzOh-yEb19D1_PqCBEHfp_Taws-u35sEfkihxTFxDmrWPehbI4spEOsncGm7g=="
        10.0.1.51:
          influxdb_token: "xdzgIZ8TJ5Ee53iRhAzoCBAqZkuObTAzr-VFd6rhErfbYSlfliOAdAE9kxs0pbAd9ZwKb4H8gqpMTH0i3sLBqQ=="
        10.0.1.80:
          influxdb_token: "-uajYiFqn0GliyhaT9ORtgeLikxCnzc1g85RK9v4pqz2mq3cOA8ZkhS7_R8MBU_YrI5rFws-o6LTkl-bqT3FAw=="
      vars:
        spring_profiles:
          container1:
            10.0.1.178: client1
            10.0.1.168: client3
            10.0.1.65: client5
            10.0.1.189: client7
            10.0.1.51: client9
            10.0.1.80: client11
          container2:
            10.0.1.178: client2
            10.0.1.168: client4
            10.0.1.65: client6
            10.0.1.189: client8
            10.0.1.51: client10
            10.0.1.80: client12
    kafka_server:
      hosts:
        10.0.1.226:
        10.0.1.225:
        10.0.1.13:
    data_division_server:
      hosts:
        10.0.1.19:
