global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'discord-webhook'
receivers:
- name: 'discord-webhook'
  webhook_configs:
  - url: 'https://discordapp.com/api/webhooks/1102766108425072671/-UyXPmGshE1Mju6WD6Rj9evO4tKsvyBzOTkF7Qc5FwKZ4fjAKG5tqkIWtY2BPCOJ0c5Z'